fix for Falcon 1.0.0 and 1.1.0
yohanboniface/falcon-multipart pull request #5
Opened 2016-12-21 03:58 UTC by kojimaeiji

this fix should also work for 0.3.0

2016-12-21 08:59 UTC, yohanboniface requested changes
Thanks!
I made a small review comment :)

2016-12-21 08:59 UTC, yohanboniface commented on falcon_multipart/middleware.py
> +        if hasattr(req.stream, 'stream'):
I'd do it a bit differently, something like:

    stream = req.stream.stream if hasattr(req.stream, 'stream') else req.stream
    form = self.parse(stream=stream, environ=req.env)

Plus I'd add a small comment to explain why we need this check.

2016-12-22 04:13 UTC, kojimaeiji commented on falcon_multipart/middleware.py
> +        if hasattr(req.stream, 'stream'):
I changed the code as you show and added a small comment for explanation above the code.

2016-12-22 10:00 UTC, yohanboniface approved these changes

2016-12-22 10:00 UTC, merged

2016-12-22 10:00 UTC, yohanboniface commented
Thanks! :)